# Usage: uv run capx/envs/launch.py --config-path env_configs/nut_assembly/franka_robosuite_nut_assembly_reduced_api.yaml

env:
  _target_: capx.envs.tasks.franka.franka_nut_assembly.FrankaNutAssemblyCodeEnv
  cfg:
    _target_: capx.envs.tasks.base.CodeExecEnvConfig
    low_level: franka_robosuite_nut_assembly_low_level_visual  # Use Robosuite instead of MuJoCo!
    privileged: false
    apis:
      - FrankaControlNutAssemblyApiReduced
    # prompt is inherited from FrankaNutAssemblyCodeEnv class default

api_servers:
  - _target_: capx.serving.launch_sam3_server.main
    device: cuda
    port: 8114
    host: 127.0.0.1
    
  - _target_: capx.serving.launch_contact_graspnet_server.main
    port: 8115
    host: 127.0.0.1
    
  - _target_: capx.serving.launch_pyroki_server.main
    port: 8116
    host: 127.0.0.1
    robot: panda_description
    target_link: panda_hand
    
record_video: true

output_dir: ./outputs/franka_robosuite_nut_assembly_reduced_api
use_oracle_code: false
trials: 100
num_workers: 12
